var destroy = document.getElementByTagName("h1");
var table = "<table>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "        <tr>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "            <td></td>\n" +
    "        </tr>\n" +
    "    </table>";

destroy.innerHTML(table);